version: '3.9'

services:
  db:
    image: mariadb:10.9.3 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3030:80
    environment:
      - PMA_PORT=3308
      - PMA_USER=root
      - PMA_PASSWORD=1234
      - UPLOAD_LIMIT=300M
